name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: 22
        cache: 'yarn'
    - name: Install packages
      run: yarn install --immutable
    - name: Run tests
      run: yarn test
